<?xml version="1.0" encoding="utf-8"?><Database Name="IWorld" Class="MainDatadbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAGICVR-PC;Initial Catalog=IWorld;Integrated Security=True" SettingsObjectName="Client.Model.Properties.Settings" SettingsPropertyName="IWorldConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IWorld_Author" Member="IWorld_Author">
    <Type Name="IWorld_Author">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SafeCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BindingEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAgents" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NormalReturnPoints" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UncertainReturnPoints" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Money" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MoneyBeFrozen" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Consumption" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Integral" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Holder" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Card" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Bank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BindingCard" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxOfSubordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginIp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LeftKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RightKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Layer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tree" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IWorld_Administrator" Member="IWorld_Administrator">
    <Type Name="IWorld_Administrator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastLoginTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginIp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>